[package]
name = "stulp-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
std = []

[dependencies]
stulp-core = { path = "../core" }
stulp-runtime = { path = "../runtime" }
stulp-web = { path = "../web" }
stulp-sdk = { path = "../sdk" }
stulp-protocol = { path = "../protocol" }
libm = { version = "=0.2.16", default-features = false }

[lints]
workspace = true
