[package]
name = "stulp-persist-check"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
stulp-hopos = { path = "../hopos" }
stulp-core = { path = "../core" }
applib = { git = "https://github.com/xinix00/HopOS.git", tag = "v3.0.10" }

[lints]
workspace = true
