[package]
name = "stulp-plugin-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
stulp-transport = { path = "../transport" }
stulp-platform = { path = "../platform" }
stulp-sdk = { path = "../sdk" }
stulp-core = { path = "../core" }
stulp-protocol = { path = "../protocol" }
hostnet = { git = "https://github.com/xinix00/hop.git", tag = "v3.0.0-alpha.10" }

leanhttp = { git = "https://github.com/xinix00/lean.git", tag = "v3.1.5" }
leantls = { git = "https://github.com/xinix00/lean.git", tag = "v3.1.5" }

[lints]
workspace = true
