[package]
name = "stulp-tls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
p256 = { version = "=0.13.2", default-features = false, features = ["ecdsa", "ecdh", "pkcs8", "alloc"] }
zeroize = { version = "=1.9.0", default-features = false, features = ["alloc"] }

p384 = { version = "=0.13.1", default-features = false, features = ["ecdsa", "pkcs8", "alloc"] }
rsa = { version = "=0.9.10", default-features = false, features = ["sha2"] }
ed25519-dalek = { version = "=2.2.0", default-features = false, features = ["alloc", "pkcs8", "zeroize"] }
rand_chacha = { version = "=0.3.1", default-features = false }
sha2 = { version = "=0.10.9", default-features = false }

[lints]
workspace = true
