[package]
name = "stulp-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rand_chacha = { version = "=0.3.1", default-features = false }
rand_core = { version = "=0.6.4", default-features = false }
hop-sync = { package = "sync", git = "https://github.com/xinix00/HopOS.git", tag = "v3.0.10" }
stulp-core = { path = "../core" }
stulp-protocol = { path = "../protocol" }

[lints]
workspace = true

[dev-dependencies]
hostnet = { git = "https://github.com/xinix00/hop.git", tag = "v3.0.0-alpha.10" }
