//! Exacte registeradressen en schalen uit plugins/sigenergy/internal/sigen/map.go.
use super::register::{Kind, Reg};
pub(super) const PLANT: &[Reg] = &[
    Reg {
        name: "GridPower",
        class: "reading",
        addr: 30005,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "GridStatus",
        class: "reading",
        addr: 30009,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "BatterySoC",
        class: "reading",
        addr: 30014,
        count: 1,
        kind: Kind::U16,
        gain: 10.0,
    },
    Reg {
        name: "SolarPower",
        class: "reading",
        addr: 30035,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "BatteryPower",
        class: "reading",
        addr: 30037,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "ThirdPartyInverterPower",
        class: "reading",
        addr: 30194,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "GeneralLoadPower",
        class: "reading",
        addr: 30282,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
];
pub(super) const INVERTER: &[Reg] = &[
    Reg {
        name: "Serial",
        class: "info",
        addr: 30515,
        count: 10,
        kind: Kind::Text,
        gain: 1.0,
    },
    Reg {
        name: "OutputType",
        class: "info",
        addr: 31004,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "MPPTCount",
        class: "info",
        addr: 31026,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "PhaseAVoltage",
        class: "reading",
        addr: 31011,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "PhaseBVoltage",
        class: "reading",
        addr: 31013,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "PhaseCVoltage",
        class: "reading",
        addr: 31015,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "PhaseACurrent",
        class: "reading",
        addr: 31017,
        count: 2,
        kind: Kind::I32,
        gain: 100.0,
    },
    Reg {
        name: "PhaseBCurrent",
        class: "reading",
        addr: 31019,
        count: 2,
        kind: Kind::I32,
        gain: 100.0,
    },
    Reg {
        name: "PhaseCCurrent",
        class: "reading",
        addr: 31021,
        count: 2,
        kind: Kind::I32,
        gain: 100.0,
    },
    Reg {
        name: "PV1Voltage",
        class: "reading",
        addr: 31027,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "PV2Voltage",
        class: "reading",
        addr: 31029,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "PV3Voltage",
        class: "reading",
        addr: 31031,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "PV4Voltage",
        class: "reading",
        addr: 31033,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "Power",
        class: "reading",
        addr: 31035,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "DailyYield",
        class: "reading",
        addr: 31509,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "TotalYield",
        class: "reading",
        addr: 31511,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
];
pub(super) const BATTERY: &[Reg] = &[
    Reg {
        name: "Serial",
        class: "info",
        addr: 30515,
        count: 10,
        kind: Kind::Text,
        gain: 1.0,
    },
    Reg {
        name: "Capacity",
        class: "info",
        addr: 30548,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "Power",
        class: "system",
        addr: 30037,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "Firmware",
        class: "reading",
        addr: 30525,
        count: 15,
        kind: Kind::Text,
        gain: 1.0,
    },
    Reg {
        name: "TotalCharged",
        class: "reading",
        addr: 30568,
        count: 4,
        kind: Kind::U64,
        gain: 100.0,
    },
    Reg {
        name: "TotalDischarged",
        class: "reading",
        addr: 30574,
        count: 4,
        kind: Kind::U64,
        gain: 100.0,
    },
    Reg {
        name: "Status",
        class: "reading",
        addr: 30578,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "SoC",
        class: "reading",
        addr: 30601,
        count: 1,
        kind: Kind::U16,
        gain: 10.0,
    },
    Reg {
        name: "MaxCellTemp",
        class: "reading",
        addr: 30620,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "MinCellTemp",
        class: "reading",
        addr: 30621,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
    Reg {
        name: "PCSTemp",
        class: "reading",
        addr: 31003,
        count: 1,
        kind: Kind::I16,
        gain: 10.0,
    },
];
pub(super) const ENERGY: &[Reg] = &[
    Reg {
        name: "Power",
        class: "reading",
        addr: 30005,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "GridStatus",
        class: "system",
        addr: 30009,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "PowerL1",
        class: "reading",
        addr: 30052,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "PowerL2",
        class: "reading",
        addr: 30054,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "PowerL3",
        class: "reading",
        addr: 30056,
        count: 2,
        kind: Kind::I32,
        gain: 1.0,
    },
    Reg {
        name: "TotalImport",
        class: "reading",
        addr: 30260,
        count: 4,
        kind: Kind::U64,
        gain: 100.0,
    },
    Reg {
        name: "TotalExport",
        class: "reading",
        addr: 30264,
        count: 4,
        kind: Kind::U64,
        gain: 100.0,
    },
    Reg {
        name: "PhaseControl",
        class: "reading",
        addr: 40030,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
];
pub(super) const EVACCHARGER: &[Reg] = &[
    Reg {
        name: "Status",
        class: "reading",
        addr: 32000,
        count: 1,
        kind: Kind::U16,
        gain: 1.0,
    },
    Reg {
        name: "TotalCharged",
        class: "reading",
        addr: 32001,
        count: 2,
        kind: Kind::U32,
        gain: 100.0,
    },
    Reg {
        name: "Power",
        class: "reading",
        addr: 32003,
        count: 2,
        kind: Kind::I32,
        gain: 1000.0,
    },
];
